export type Locale = "ar" | "en";

export const content = {
  ar: {
    dir: "rtl" as const,
    brand: { name: "سوار الذهب", tagline: "أسواقٌ من ذهب" },
    intro: {
      skip: "تخطّي المقدمة",
      progress: "تجربة تفاعلية",
      scenes: [
        { title: "سوار الذهب", subtitle: "حيث يبدأ بريق القصة" },
        { title: "اقترب من أسواق الذهب", subtitle: "أحسّ بأجواء السوق وهي تتجسّد حولك" },
        { title: "تجوّل بين أروقة السوق", subtitle: "ممرّات تلمع بالذهب من كل جانب" },
        { title: "محلٌّ ينتظرك", subtitle: "أحد أفخم متاجر الذهب يدعوك للدخول" },
      ],
      door: "ادخل إلى الأسواق",
      doorHint: "اضغط لتكتشف عالم سوار الذهب",
    },
    nav: {
      links: [
        { id: "about", label: "عن المشروع" },
        { id: "markets", label: "الأسواق" },
        { id: "experiences", label: "التجارب" },
        { id: "values", label: "قيمنا" },
        { id: "news", label: "الأخبار" },
        { id: "contact", label: "تواصل" },
      ],
      cta: "احجز جولتك",
    },
    hero: {
      eyebrow: "وجهةٌ ذهبية استثنائية",
      title: "حيث يلتقي بريق الذهب بأصالة السوق",
      subtitle:
        "سوار الذهب — مشروع أسواق ذهب فاخرة يعيد تعريف تجربة التسوق، حيث تتجسّد الحِرفية الأصيلة في تفاصيل تأسر الأنظار.",
      ctaPrimary: "اكتشف الأسواق",
      ctaSecondary: "تعرّف على المشروع",
      scroll: "اسحب للأسفل",
    },
    about: {
      eyebrow: "رؤيتنا",
      title: "إرثٌ من الذهب يُروى تفصيلةً تفصيلة",
      lead: "وُلد سوار الذهب من شغفٍ بإحياء روح الأسواق التراثية، حيث تلتقي الحِرفية اليدوية بفخامة التجربة العصرية.",
      paragraphs: [
        "نؤمن أن تجربة التسوّق الحقيقية تبدأ من اللحظة الأولى. لذلك صمّمنا وجهةً متكاملة تجمع نخبة متاجر الذهب تحت سقفٍ واحد، بخبرةٍ توارثتها الأجيال.",
        "انطلاقاً من رؤيتنا، جمعنا أمهر الصاغة وأرقى العلامات ليصبح سوار الذهب الوجهة الأولى لعشّاق الذهب في المنطقة.",
      ],
      signature: "رئيس مجلس الإدارة",
      signatory: "أبو محمد الذهبي",
    },
    vision: {
      eyebrow: "الرؤية والمهمة",
      title: "أن نصنع الوجهة الذهبية الأولى في المنطقة",
      body: "رؤيتنا أن نكون أكبر تجمّعٍ لأسواق الذهب الفاخرة، عبر توظيف خبراتنا وشراكاتنا لنقدّم تجربة تسوّقٍ لا تُنسى تُحتذى عالمياً.",
      mission: {
        title: "مهمتنا",
        body: "لا تقتصر مهمتنا على بيع الذهب فحسب، بل نلتزم بصياغة تجربةٍ استثنائية تدعم الاقتصاد وتُحيي الحِرف التقليدية وترفع قطاع التجارة في المملكة.",
      },
    },
    stats: {
      title: "خبرةٌ تتلألأ بالذهب",
      subtitle: "نحوّل الرؤية إلى واقعٍ ملموس عبر أسواقٍ ومعارض رفعت معايير التجارة.",
      items: [
        { value: 120, suffix: "+", label: "متجر ذهب", prefix: "" },
        { value: 8, suffix: "", label: "أسواق متخصصة", prefix: "" },
        { value: 2, suffix: "B", label: "ريال حجم الاستثمارات", prefix: "" },
        { value: 25, suffix: "", label: "عاماً من الخبرة", prefix: "" },
      ],
    },
    markets: {
      eyebrow: "أسواقنا",
      title: "أسواقٌ تأسر القلوب",
      subtitle: "اكتشف مجموعة أسواقنا المتخصصة، حيث يلمع الذهب في كل زاوية.",
      cta: "اكتشف السوق",
      items: [
        { name: "سوق الذهب الكبير", tag: "السوق الرئيسي", desc: "أكبر تجمّع لمتاجر الذهب الخالص بأفخم التصاميم." },
        { name: "سوق الحِرفية", tag: "صياغة يدوية", desc: "ورش الصياغة التقليدية حيث يُصاغ الذهب بأيدٍ ماهرة." },
        { name: "بهاء المجوهرات", tag: "مجوهرات فاخرة", desc: "نخبة العلامات العالمية للمجوهرات والأحجار الكريمة." },
        { name: "رواق التحف", tag: "قطع نادرة", desc: "تحفٍ ذهبية ومقتنياتٍ نادرة للعارفين بالقيمة." },
        { name: "سوق العيار", tag: "تجارة الذهب", desc: "مركزٌ متخصص بتجارة الذهب بالأوزان والأسعار الحيّة." },
        { name: "دار الإبداع", tag: "تصاميم حصرية", desc: "تصاميم ذهبية حصرية لا تجدها إلا في سوار الذهب." },
      ],
    },
    experiences: {
      eyebrow: "التجارب",
      title: "تجاربٌ تستحقّ أن تُعاش",
      subtitle: "كل تفصيلة في أسواقنا مصمّمة لمنحك تجربةً حسيةً متكاملة.",
      items: [
        { title: "صياغة على الهواء", desc: "شاهد الصاغة وهم يُبدعون القطع الذهبية أمام عينيك." },
        { title: "جولاتٌ مرافقة", desc: "جولاتٌ خاصة بمرشدين خبراء يعرّفونك على أسرار السوق." },
        { title: "ضيافةٌ ملكية", desc: "أجنحة استراحة فاخرة تقدّم القهوة العربية والتمر للضيوف." },
        { title: "تصاميم حصرية", desc: "صمّم قطعتك الذهبية الخاصة مع نخبة المصممين." },
      ],
    },
    values: {
      eyebrow: "قيمنا",
      title: "قيمٌ تُلهم كل قطعة ذهب",
      subtitle: "خمسةُ مبادئ توجّه رؤيتنا وتُشكّل هويتنا.",
      items: [
        { title: "الأصالة", desc: "نحافظ على الحِرفية التقليدية في كل قطعةٍ نقدّمها." },
        { title: "الإتقان", desc: "في تفاصيلٍ لا تخطئها العين المهتمة." },
        { title: "الثقة", desc: "نكسب ثقة عملائنا بشفافيةٍ تامة في كل تعامل." },
        { title: "الفخامة", desc: "تجربةٌ راقية من اللحظة الأولى حتى الأخيرة." },
        { title: "الابتكار", desc: "نمزج عراقة الذهب بلمسات التصميم العصري." },
      ],
    },
    testimonials: {
      eyebrow: "آراء زوّارنا",
      title: "قصصٌ من زوّارٍ عاشوا التجربة",
      items: [
        { quote: "تجربةٌ فاقت توقعاتي. شعرتُ وكأنني أدخل كنزاً من الذهب.", name: "نورة العتيبي", role: "زائرة دائمة" },
        { quote: "المزج بين الأصالة والفخامة جعل من زيارتي شيئاً لا يُنسى.", name: "خالد المنصور", role: "تاجر ذهب" },
        { quote: "خدمةٌ بمستوى ملكي، وأسواقٌ لا مثيل لها في المنطقة.", name: "سارة الدوسري", role: "مصمّمة مجوهرات" },
      ],
    },
    news: {
      eyebrow: "الأخبار",
      title: "آخر أخبار سوار الذهب",
      items: [
        { title: "افتتاح سوق الذهب الكبير في قلب الرياض", date: "نوفمبر 2025", tag: "افتتاح" },
        { title: "استثماراتنا تتجاوز ملياري ريال", date: "أكتوبر 2025", tag: "أعمال" },
        { title: "شراكةٌ مع نخبة الصاغة المحليين", date: "سبتمبر 2025", tag: "شراكات" },
      ],
    },
    contact: {
      eyebrow: "تواصل معنا",
      title: "لنصنع تجربتك الذهبية القادمة",
      subtitle: "لجميع الاستفسارات حول الأسواق والجولات، نحن هنا لخدمتك.",
      form: {
        subject: "موضوع الطلب",
        subjectOptions: ["استفسار عن جولة", "استفسار عن سوق", "استفسارات عامة", "وظائف", "خدمة العملاء"],
        name: "الاسم الكامل",
        email: "البريد الإلكتروني",
        phone: "رقم الهاتف",
        message: "رسالتك",
        consent: "أنا ملتزم بشروط اتفاقية الخدمة وأوافق على سياسة الخصوصية",
        submit: "إرسال",
      },
      info: {
        email: "info@suweraldhahab.sa",
        phone: "+966 11 655 5555",
        address: "الرياض، المملكة العربية السعودية",
      },
    },
    footer: {
      about: "سوار الذهب — وجهةٌ ذهبية فاخرة، تجمع نخبة أسواق الذهب تحت سقفٍ واحد بأعلى معايير الحِرفية والجودة.",
      rights: "جميع الحقوق محفوظة",
      newsletter: "النشرة الإخبارية",
      newsletterCta: "سجّل",
      quickLinks: "روابط سريعة",
    },
    auth: {
      loginTitle: "تسجيل الدخول",
      registerTitle: "إنشاء حساب",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      name: "الاسم الكامل",
      role: "نوع الحساب",
      guest: "ضيف",
      hotelier: "صاحب فندق",
      loginBtn: "دخول",
      registerBtn: "تسجيل",
      noAccount: "ليس لديك حساب؟",
      haveAccount: "لديك حساب؟",
      registerLink: "أنشئ حساباً",
      loginLink: "سجّل الدخول",
    },
    search: {
      title: "ابحث عن غرفة",
      destination: "الوجهة",
      checkIn: "تاريخ الوصول",
      checkOut: "تاريخ المغادرة",
      guests: "عدد الضيوف",
      searchBtn: "بحث",
      noResults: "لا توجد غرف متاحة لهذه التواريخ",
      perNight: "لليلة",
      availableRooms: "غرف متاحة",
      bookNow: "احجز الآن",
    },
    booking: {
      title: "إكمال الحجز",
      guestDetails: "بيانات الضيف",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      phone: "رقم الهاتف",
      payment: "الدفع",
      orderSummary: "ملخص الطلب",
      roomType: "نوع الغرفة",
      quantity: "الكمية",
      nights: "الليالي",
      total: "الإجمالي",
      confirmBooking: "تأكيد الحجز",
      confirmation: "تم تأكيد حجزك بنجاح",
      bookingId: "رقم الحجز",
      myBookings: "حجوزاتي",
      status: "الحالة",
      cancel: "إلغاء",
      cancelConfirm: "هل أنت متأكد من إلغاء هذا الحجز؟",
      cancelled: "تم الإلغاء",
      refund: "المبلغ المسترد",
    },
    dashboard: {
      title: "لوحة تحكم الفندق",
      overview: "نظرة عامة",
      rooms: "الغرف",
      calendar: "التقويم",
      bookings: "الحجوزات",
      roomTypes: "أنواع الغرف",
      rates: "الأسعار",
      addRoomType: "إضافة نوع غرفة",
      addRoom: "إضافة غرفة",
      roomNumber: "رقم الغرفة",
      floor: "الطابق",
      capacity: "السعة",
      basePrice: "السعر الأساسي",
      bedType: "نوع السرير",
      checkIn: "تسجيل الوصول",
      checkOut: "تسجيل المغادرة",
      payouts: "المدفوعات",
    },
    admin: {
      title: "لوحة الإدارة",
      hotels: "الفنادق",
      users: "المستخدمون",
      reports: "التقارير",
      approve: "موافقة",
      suspend: "تعليق",
      reinstate: "إعادة تفعيل",
      pending: "قيد المراجعة",
      active: "نشط",
      suspended: "معلّق",
      totalBookings: "إجمالي الحجوزات",
      totalRevenue: "إجمالي الإيرادات",
      cancellationRate: "معدل الإلغاء",
    },
  },
  en: {
    dir: "ltr" as const,
    brand: { name: "Suwar Al Dhahab", tagline: "Markets of Gold" },
    intro: {
      skip: "Skip Intro",
      progress: "Interactive Experience",
      scenes: [
        { title: "Suwar Al Dhahab", subtitle: "Where the story begins to gleam" },
        { title: "Approach the Gold Markets", subtitle: "Feel the souk come alive around you" },
        { title: "Stroll Through the Passages", subtitle: "Corridores gleaming with gold on every side" },
        { title: "A Shop Awaits You", subtitle: "One of the finest gold boutiques invites you in" },
      ],
      door: "Enter the Markets",
      doorHint: "Click to step into the world of Suwar Al Dhahab",
    },
    nav: {
      links: [
        { id: "about", label: "The Project" },
        { id: "markets", label: "Markets" },
        { id: "experiences", label: "Experiences" },
        { id: "values", label: "Values" },
        { id: "news", label: "News" },
        { id: "contact", label: "Contact" },
      ],
      cta: "Book a Tour",
    },
    hero: {
      eyebrow: "An Exceptional Golden Destination",
      title: "Where the Gleam of Gold Meets the Soul of the Souk",
      subtitle:
        "Suwar Al Dhahab — a luxury gold-market destination redefining the shopping experience, where craftsmanship is etched into every captivating detail.",
      ctaPrimary: "Discover the Markets",
      ctaSecondary: "About the Project",
      scroll: "Scroll Down",
    },
    about: {
      eyebrow: "Our Vision",
      title: "A Legacy of Gold, Told Detail by Detail",
      lead: "Suwar Al Dhahab was born from a passion to revive the spirit of heritage markets, where traditional craftsmanship meets the refinement of modern experience.",
      paragraphs: [
        "We believe a true shopping experience begins in the very first moment. So we designed an integrated destination that gathers elite gold boutiques under one roof, with expertise passed down through generations.",
        "Driven by our vision, we assembled the most skilled artisans and the finest brands, making Suwar Al Dhahab the leading destination for gold lovers in the region.",
      ],
      signature: "Chairman of the Board",
      signatory: "Abu Mohammed Al-Dhahabi",
    },
    vision: {
      eyebrow: "Vision & Mission",
      title: "Crafting the Region's Premier Golden Destination",
      body: "Our vision is to be the largest cluster of luxury gold markets, leveraging our expertise and partnerships to offer an unforgettable shopping experience emulated worldwide.",
      mission: {
        title: "Our Mission",
        body: "Our mission extends beyond selling gold. We are committed to crafting an exceptional experience that supports the economy, revives traditional crafts, and elevates the trade sector in the Kingdom.",
      },
    },
    stats: {
      title: "Expertise That Gleams With Gold",
      subtitle: "We turn vision into reality through markets and galleries that raised trade standards.",
      items: [
        { value: 120, suffix: "+", label: "Gold Boutiques", prefix: "" },
        { value: 8, suffix: "", label: "Specialized Markets", prefix: "" },
        { value: 2, suffix: "B", label: "SAR Investment Volume", prefix: "" },
        { value: 25, suffix: "", label: "Years of Expertise", prefix: "" },
      ],
    },
    markets: {
      eyebrow: "Our Markets",
      title: "Markets That Capture Hearts",
      subtitle: "Discover our curated collection of specialized markets, where gold gleams in every corner.",
      cta: "Discover Market",
      items: [
        { name: "The Grand Gold Souk", tag: "Main Market", desc: "The largest gathering of pure-gold boutiques with the finest designs." },
        { name: "Craftsmanship Souk", tag: "Handcrafting", desc: "Traditional crafting workshops where gold is shaped by skilled hands." },
        { name: "Splendor Jewellery", tag: "Luxury Jewellery", desc: "Elite global brands for jewellery and precious stones." },
        { name: "Heritage Gallery", tag: "Rare Pieces", desc: "Golden artifacts and rare collectibles for those who know true value." },
        { name: "Karat Market", tag: "Gold Trade", desc: "A specialized center for gold trading by weight and live prices." },
        { name: "House of Creation", tag: "Exclusive Designs", desc: "Exclusive gold designs found only at Suwar Al Dhahab." },
      ],
    },
    experiences: {
      eyebrow: "Experiences",
      title: "Experiences Worth Living",
      subtitle: "Every detail in our markets is designed to offer a complete sensory journey.",
      items: [
        { title: "Live Craftsmanship", desc: "Watch artisans craft golden pieces before your eyes." },
        { title: "Guided Tours", desc: "Private tours with expert guides revealing the souk's secrets." },
        { title: "Royal Hospitality", desc: "Luxury lounge areas serving Arabic coffee and dates to guests." },
        { title: "Bespoke Designs", desc: "Design your own golden piece with elite designers." },
      ],
    },
    values: {
      eyebrow: "Our Values",
      title: "Values That Inspire Every Golden Piece",
      subtitle: "Five principles guiding our vision and shaping our identity.",
      items: [
        { title: "Authenticity", desc: "Preserving traditional craftsmanship in every piece we offer." },
        { title: "Mastery", desc: "In details that a discerning eye never misses." },
        { title: "Trust", desc: "Earning our clients' trust with full transparency." },
        { title: "Luxury", desc: "A refined experience from the first moment to the last." },
        { title: "Innovation", desc: "Blending gold's heritage with contemporary design." },
      ],
    },
    testimonials: {
      eyebrow: "Visitor Stories",
      title: "Stories From Visitors Who Lived the Experience",
      items: [
        { quote: "An experience that surpassed my expectations. I felt as if I stepped into a treasure of gold.", name: "Noura Al-Otaibi", role: "Returning Visitor" },
        { quote: "The blend of authenticity and luxury made my visit truly unforgettable.", name: "Khalid Al-Mansour", role: "Gold Trader" },
        { quote: "Royal-level service, and markets with no equal in the region.", name: "Sara Al-Dosari", role: "Jewellery Designer" },
      ],
    },
    news: {
      eyebrow: "News",
      title: "Latest From Suwar Al Dhahab",
      items: [
        { title: "Opening the Grand Gold Souk in the Heart of Riyadh", date: "November 2025", tag: "Opening" },
        { title: "Our Investments Exceed Two Billion SAR", date: "October 2025", tag: "Business" },
        { title: "Partnership With Elite Local Artisans", date: "September 2025", tag: "Partnerships" },
      ],
    },
    contact: {
      eyebrow: "Contact Us",
      title: "Let's Craft Your Next Golden Experience",
      subtitle: "For all inquiries about markets and tours, we are here to serve you.",
      form: {
        subject: "Request Subject",
        subjectOptions: ["Tour Inquiry", "Market Inquiry", "General Inquiries", "Careers", "Customer Service"],
        name: "Full Name",
        email: "Email Address",
        phone: "Phone Number",
        message: "Your Message",
        consent: "I am committed to the Terms of Service and agree to the Privacy Policy",
        submit: "Send",
      },
      info: {
        email: "info@suweraldhahab.sa",
        phone: "+966 11 655 5555",
        address: "Riyadh, Kingdom of Saudi Arabia",
      },
    },
    footer: {
      about: "Suwar Al Dhahab — a luxury golden destination gathering elite gold markets under one roof with the highest standards of craftsmanship and quality.",
      rights: "All Rights Reserved",
      newsletter: "Newsletter",
      newsletterCta: "Subscribe",
      quickLinks: "Quick Links",
    },
    auth: {
      loginTitle: "Log In",
      registerTitle: "Create Account",
      email: "Email Address",
      password: "Password",
      name: "Full Name",
      role: "Account Type",
      guest: "Guest",
      hotelier: "Hotelier",
      loginBtn: "Log In",
      registerBtn: "Register",
      noAccount: "Don't have an account?",
      haveAccount: "Already have an account?",
      registerLink: "Create one",
      loginLink: "Log in",
    },
    search: {
      title: "Search Rooms",
      destination: "Destination",
      checkIn: "Check-in Date",
      checkOut: "Check-out Date",
      guests: "Number of Guests",
      searchBtn: "Search",
      noResults: "No rooms available for these dates",
      perNight: "per night",
      availableRooms: "rooms available",
      bookNow: "Book Now",
    },
    booking: {
      title: "Complete Booking",
      guestDetails: "Guest Details",
      fullName: "Full Name",
      email: "Email Address",
      phone: "Phone Number",
      payment: "Payment",
      orderSummary: "Order Summary",
      roomType: "Room Type",
      quantity: "Quantity",
      nights: "nights",
      total: "Total",
      confirmBooking: "Confirm Booking",
      confirmation: "Your booking has been confirmed",
      bookingId: "Booking ID",
      myBookings: "My Bookings",
      status: "Status",
      cancel: "Cancel",
      cancelConfirm: "Are you sure you want to cancel this booking?",
      cancelled: "Cancelled",
      refund: "Refund Amount",
    },
    dashboard: {
      title: "Hotelier Dashboard",
      overview: "Overview",
      rooms: "Rooms",
      calendar: "Calendar",
      bookings: "Bookings",
      roomTypes: "Room Types",
      rates: "Rates",
      addRoomType: "Add Room Type",
      addRoom: "Add Room",
      roomNumber: "Room Number",
      floor: "Floor",
      capacity: "Capacity",
      basePrice: "Base Price",
      bedType: "Bed Type",
      checkIn: "Check-in",
      checkOut: "Check-out",
      payouts: "Payouts",
    },
    admin: {
      title: "Admin Console",
      hotels: "Hotels",
      users: "Users",
      reports: "Reports",
      approve: "Approve",
      suspend: "Suspend",
      reinstate: "Reinstate",
      pending: "Pending",
      active: "Active",
      suspended: "Suspended",
      totalBookings: "Total Bookings",
      totalRevenue: "Total Revenue",
      cancellationRate: "Cancellation Rate",
    },
  },
} as const;

export type Content = (typeof content)["ar"];
