export type Locale = "ar" | "en";

export const content = {
  ar: {
    dir: "rtl" as const,
    brand: { name: "سوار الأندلس", tagline: "ضيافةٌ بأناقة الأندلس" },
    intro: {
      skip: "تخطّي المقدمة",
      progress: "تجربة تفاعلية",
      scenes: [
        { title: "سوار الأندلس", subtitle: "حيث تبدأ الرحلة" },
        { title: "اقترب من الفندق", subtitle: "استشعر أجواء الاستقبال وهي تتجسّد حولك" },
        { title: "صالة الاستقبال", subtitle: "مساحة ترحاب بأناقة الأندلس" },
        { title: "غرفتك تنتظرك", subtitle: "إقامة فاخرة تدعوك للراحة" },
      ],
      door: "ادخل إلى الفندق",
      doorHint: "اضغط لتبدأ إقامتك مع سوار الأندلس",
    },
    nav: {
      links: [
        { id: "rooms", label: "الغرف والأجنحة" },
        { id: "featured", label: "الفنادق المميزة" },
        { id: "experiences", label: "التجارب" },
        { id: "why", label: "لماذا نحن" },
        { id: "stories", label: "آراء الضيوف" },
        { id: "contact", label: "تواصل" },
      ],
      cta: "احجز إقامتك",
      allRooms: "كل الغرف والأجنحة",
    },
    hero: {
      eyebrow: "ضيافةٌ بأناقة الأندلس",
      title: "إقامةٌ فاخرة تُروى كقصيدة",
      subtitle:
        "سوار الأندلس — وجهة ضيافة راقية تجمع نخبة الفنادق المختارة بعناية، حيث تلتقي الدفء الأندلسية بأرقى تفاصيل الراحة.",
      ctaPrimary: "ابحث عن غرفتك",
      ctaSecondary: "تعرّف علينا",
      scroll: "اسحب للأسفل",
    },
    about: {
      eyebrow: "قصتنا",
      title: "إرثٌ من الضيافة يُروى تفصيلةً تفصيلة",
      lead: "وُلد سوار الأندلس من شغفٍ بإحياء روح الضيافة الأندلسية، حيث تلتقي الحِرفة الأصيلة بفخامة التجربة العصرية.",
      paragraphs: [
        "نؤمن أن الإقامة الحقيقية تبدأ من اللحظة الأولى. لذلك صمّمنا وجهةً متكاملة تجمع نخبة الفنادق تحت سقفٍ واحد، بخبرةٍ توارثتها الأجيال.",
        "انطلاقاً من رؤيتنا، جمعنا أرقى الفنادق وأمهر فرق الضيافة ليصبح سوار الأندلس الوجهة الأولى لعشّاق الراحة والأناقة.",
      ],
      signature: "رئيس مجلس الإدارة",
      signatory: "أبو محمد الأندلسي",
    },
    vision: {
      eyebrow: "الرؤية والمهمة",
      title: "أن نصنع وجهة الضيافة الأولى في المنطقة",
      body: "رؤيتنا أن نكون أرقى تجمّعٍ للفنادق الفاخرة، عبر توظيف خبراتنا وشراكاتنا لنقدّم تجربة إقامةٍ لا تُنسى تُحتذى عالمياً.",
      mission: {
        title: "مهمتنا",
        body: "لا تقتصر مهمتنا على توفير الغرف فحسب، بل نلتزم بصياغة تجربةٍ استثنائية تدعم السياحة وتُحيي فنون الضيافة وترفع قطاع الفندقة في المملكة.",
      },
    },
    stats: {
      title: "خبرةٌ تُؤتى ثمارها",
      subtitle: "نحوّل الرؤية إلى واقعٍ ملموس عبر فنادق رفعت معايير الضيافة.",
      items: [
        { value: 5, suffix: "", label: "فنادق مختارة", prefix: "" },
        { value: 320, suffix: "+", label: "غرفة وجناح", prefix: "" },
        { value: 4.9, suffix: "", label: "متوسط التقييم", prefix: "" },
        { value: 12, suffix: "", label: "عاماً من الضيافة", prefix: "" },
      ],
    },
    markets: {
      eyebrow: "وجهاتنا",
      title: "وجهاتٌ تأسر القلوب",
      subtitle: "اكتشف مجموعتنا من الفنادق في أرقى المدن، حيث تلتقي الأناقة بالراحة.",
      cta: "اكتشف الوجهة",
      items: [
        { name: "سوار الرياض", tag: "الرياض", desc: "فندق فاخر في قلب العاصمة بإطلالات ساحرة على المدينة." },
        { name: "سوار جدة", tag: "جدة", desc: "إقامة على الواجهة البحرية بلمسة من عبق البحر الأحمر." },
        { name: "سوار مكة", tag: "مكة المكرمة", desc: "قربٌ من الحرم وخدمات ضيافة تليق بالزائر." },
        { name: "سوار المدينة", tag: "المدينة المنورة", desc: "هدوءٌ وطمأنينة على بعد خطوات من المسجد النبوي." },
        { name: "سوار العُلا", tag: "العُلا", desc: "ملاذٌ صحراوي بين الجبال والآثار التاريخية." },
        { name: "سوار البحر الأحمر", tag: "البحر الأحمر", desc: "منتجعٌ ساحلي يجمع الفخامة بالنقاء الطبيعي." },
      ],
    },
    experiences: {
      eyebrow: "التجارب",
      title: "تجاربٌ تستحقّ أن تُعاش",
      subtitle: "كل تفصيلة في فنادقنا مصمّمة لمنحك تجربةً متكاملة لا تُنسى.",
      items: [
        { title: "منتجعات صحية", desc: "سبا ومرافق عافية عالمية لاستعادة التوازن والراحة." },
        { title: "مطاعم ذواقة", desc: "أطباقٌ إبداعية من نخبة الطهاة في أجواءٍ راقية." },
        { title: "كونسيرج خاص", desc: "خدمة كونسيرج ملكية على مدار الساعة لكل تفاصيل إقامتك." },
        { title: "أنشطة ترفيهية", desc: "جولاتٌ ومناسبات وأنشطة مصمّمة لكل ضيف." },
      ],
    },
    values: {
      eyebrow: "قيمنا",
      title: "قيمٌ تُلهم كل إقامة",
      subtitle: "خمسةُ مبادئ توجّه رؤيتنا وتُشكّل هويتنا.",
      items: [
        { title: "الضيافة", desc: "نستقبل ضيوفنا كرامٍ بأناقة الأندلس الأصيلة." },
        { title: "الإتقان", desc: "في تفاصيلٍ لا تخطئها العين المهتمة." },
        { title: "الثقة", desc: "نكسب ثقة ضيوفنا بشفافيةٍ تامة في كل تعامل." },
        { title: "الفخامة", desc: "تجربةٌ راقية من اللحظة الأولى حتى الأخيرة." },
        { title: "الابتكار", desc: "نمزج عراقة الضيافة بلمحات التصميم العصري." },
      ],
    },
    testimonials: {
      eyebrow: "آراء الضيوف",
      title: "قصصٌ من ضيوفٍ عاشوا التجربة",
      items: [
        { quote: "إقامة رائعة بكل المقاييس، الخدمة كانت استثنائية!", name: "أحمد العتيبي", role: "مسافر أعمال" },
        { quote: "فندق فاخر بموقع ممتاز وفريق محترف.", name: "سارة المالكي", role: "إجازة عائلية" },
        { quote: "تجربة لا تُنسى، سنعود بالتأكيد.", name: "خالد الحربي", role: "شهر العسل" },
      ],
    },
    news: {
      eyebrow: "الأخبار",
      title: "آخر أخبار سوار الأندلس",
      items: [
        { title: "افتتاح سوار العُلا بين الجبال", date: "نوفمبر 2025", tag: "افتتاح" },
        { title: "توسّع مجموعتنا إلى ستّ مدن", date: "أكتوبر 2025", tag: "أعمال" },
        { title: "شراكةٌ مع نخبة الطهاة العالميين", date: "سبتمبر 2025", tag: "شراكات" },
      ],
    },
    contact: {
      eyebrow: "تواصل معنا",
      title: "لنصنع إقامتك القادمة",
      subtitle: "لجميع استفسارات الحجز والإقامة، نحن هنا لخدمتك.",
      form: {
        subject: "موضوع الطلب",
        subjectOptions: ["استفسار عن حجز", "استفسار عن فندق", "استفسارات عامة", "وظائف", "خدمة العملاء"],
        name: "الاسم الكامل",
        email: "البريد الإلكتروني",
        phone: "رقم الهاتف",
        message: "رسالتك",
        consent: "أنا ملتزم بشروط اتفاقية الخدمة وأوافق على سياسة الخصوصية",
        submit: "إرسال",
      },
      info: {
        email: "info@sewaralandalus.sa",
        phone: "+966 11 655 5555",
        address: "الرياض، المملكة العربية السعودية",
      },
    },
    footer: {
      about: "سوار الأندلس — وجهة ضيافةٍ راقية، تجمع نخبة الفنادق المختارة بأعلى معايير الأناقة والراحة.",
      rights: "جميع الحقوق محفوظة",
      newsletter: "النشرة الإخبارية",
      newsletterCta: "سجّل",
      quickLinks: "روابط سريعة",
    },
    auth: {
      loginTitle: "تسجيل الدخول",
      registerTitle: "إنشاء حساب",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      name: "الاسم الكامل",
      role: "نوع الحساب",
      guest: "ضيف",
      loginBtn: "دخول",
      registerBtn: "تسجيل",
      noAccount: "ليس لديك حساب؟",
      haveAccount: "لديك حساب؟",
      registerLink: "أنشئ حساباً",
      loginLink: "سجّل الدخول",
      adminLoginTitle: "دخول لوحة الإدارة",
      adminLoginSubtitle: "مخصص لطاقم الإدارة فقط",
      adminPortalLink: "دخول الإدارة",
      wrongPortalAdmin: "هذا الحساب إداري. يُرجى استخدام صفحة دخول الإدارة.",
      wrongPortalGuest: "هذا الحساب للضيوف. يُرجى استخدام صفحة دخول الضيوف.",
    },
    search: {
      title: "ابحث عن غرفة",
      destination: "الوجهة",
      checkIn: "تاريخ الوصول",
      checkOut: "تاريخ المغادرة",
      guests: "عدد الضيوف",
      searchBtn: "بحث",
      noResults: "لا توجد غرف متاحة لهذه التواريخ",
      perNight: "لليلة",
      availableRooms: "غرف متاحة",
      bookNow: "احجز الآن",
    },
    booking: {
      title: "إكمال الحجز",
      guestDetails: "بيانات الضيف",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      phone: "رقم الهاتف",
      payment: "الدفع",
      orderSummary: "ملخص الطلب",
      roomType: "نوع الغرفة",
      quantity: "الكمية",
      nights: "الليالي",
      total: "الإجمالي",
      confirmBooking: "تأكيد الحجز",
      confirmation: "تم تأكيد حجزك بنجاح",
      bookingId: "رقم الحجز",
      myBookings: "حجوزاتي",
      status: "الحالة",
      cancel: "إلغاء",
      cancelConfirm: "هل أنت متأكد من إلغاء هذا الحجز؟",
      cancelled: "تم الإلغاء",
      refund: "المبلغ المسترد",
    },
    dashboard: {
      title: "لوحة تحكم الفندق",
      overview: "نظرة عامة",
      rooms: "الغرف",
      calendar: "التقويم",
      bookings: "الحجوزات",
      roomTypes: "أنواع الغرف",
      rates: "الأسعار",
      addRoomType: "إضافة نوع غرفة",
      addRoom: "إضافة غرفة",
      roomNumber: "رقم الغرفة",
      floor: "الطابق",
      capacity: "السعة",
      basePrice: "السعر الأساسي",
      bedType: "نوع السرير",
      checkIn: "تسجيل الوصول",
      checkOut: "تسجيل المغادرة",
      payouts: "المدفوعات",
      occupancyRate: "معدل الإشغال",
      adr: "متوسط السعر اليومي",
      revpar: "الإيراد لكل غرفة متاحة",
      revenue: "الإيراد",
      cancellations: "الإلغاءات",
      recentBookings: "الحجوزات الأخيرة",
      upcomingArrivals: "القادمون",
      upcomingDepartures: "المغادرون",
      selectPeriod: "اختر الفترة",
      selectProperty: "اختر الفندق",
      noRooms: "لا توجد غرف بعد",
      noBookings: "لا توجد حجوزات بعد",
      noRates: "لا توجد أسعار بعد",
      mediaManager: "مدير الوسائط",
      uploadImage: "رفع صورة",
      captionAr: "التعليق بالعربية",
      captionEn: "التعليق بالإنجليزية",
      reorder: "إعادة ترتيب",
      deleteImage: "حذف",
      galleryTitle: "معرض الصور",
    },
    admin: {
      title: "لوحة الإدارة",
      hotels: "الفنادق",
      users: "المستخدمون",
      reports: "التقارير",
      approve: "موافقة",
      suspend: "تعليق",
      reinstate: "إعادة تفعيل",
      pending: "قيد المراجعة",
      active: "نشط",
      suspended: "معلّق",
      totalBookings: "إجمالي الحجوزات",
      totalRevenue: "إجمالي الإيرادات",
      cancellationRate: "معدل الإلغاء",
      featured: "المميزة",
      curateFeatured: "إدارة الفنادق المميزة",
      addFeatured: "إضافة للمميزة",
      removeFeatured: "إزالة من المميزة",
      reorderFeatured: "إعادة ترتيب المميزة",
      disputeCount: "عدد النزاعات",
      platformReports: "تقارير المنصة",
      perHotel: "حسب الفندق",
      roomsManagement: "إدارة الغرف والأجنحة",
      addUser: "إضافة مستخدم",
      userDetails: "تفاصيل المستخدم",
      searchUsers: "ابحث عن مستخدم...",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      role: "الدور",
      status: "الحالة",
      joined: "تاريخ التسجيل",
      guest: "ضيف",
      adminRole: "أدمن",
      bookings: "الحجوزات",
      favorites: "المفضلة",
      totalSpent: "إجمالي الإنفاق",
      noResults: "لا توجد نتائج",
      addRoomType: "إضافة نوع غرفة",
      roomNameAr: "الاسم بالعربية",
      roomNameEn: "الاسم بالإنجليزية",
      roomDescAr: "الوصف بالعربية",
      roomDescEn: "الوصف بالإنجليزية",
      capacity: "السعة",
      bedType: "نوع السرير",
      pricePerNight: "السعر لليلة",
      amenities: "المرافق",
      photos: "الصور (روابط مفصولة بفواصل)",
      photosHint: "ألصق روابط الصور مفصولة بفاصلة",
      photoUrl: "رابط الصورة",
      addPhoto: "إضافة صورة",
      save: "حفظ",
      cancel: "إلغاء",
      delete: "حذف",
      deleting: "جارٍ الحذف...",
      confirmDeleteRoom: "هل تريد حذف هذا النوع من الغرف؟ لا يمكن التراجع عن هذا الإجراء.",
      cannotDeleteBooked: "لا يمكن حذف هذا النوع لوجود حجوزات مرتبطة به.",
      roomAdded: "تمت إضافة النوع بنجاح",
      existingRooms: "الأنواع الحالية",
      selectHotel: "اختر الفندق",
      noHotels: "لا توجد فنادق",
      confirmSuspend: "هل تريد تعليق هذا الحساب؟",
      confirmReinstate: "هل تريد إعادة تفعيل هذا الحساب؟",
    },
    hotelHome: {
      featuredTitle: "فنادق مميزة",
      featuredSubtitle: "اكتشف نخبة فنادقنا المختارة بعناية",
      viewDetails: "عرض التفاصيل",
      startingFrom: "تبدأ من",
      perNight: "لليلة",
      rating: "التقييم",
      reviewsCount: "مراجعة",
      searchPlaceholder: "ابحث عن فندقك...",
      exploreMore: "اكتشف المزيد",
      noFeatured: "لا توجد فنادق مميزة حالياً",
      collections: "المجموعات",
      experiences: "التجارب",
      trustSignals: "لماذا تختارنا",
    },
    propertyDetail: {
      gallery: "معرض الصور",
      amenities: "المرافق",
      availableRooms: "الغرف المتاحة",
      reviews: "التقييمات",
      location: "الموقع",
      getDirections: "احصل على الاتجاهات",
      nearbyLandmarks: "معالم قريبة",
      hostInfo: "معلومات المضيف",
      policies: "سياسات الفندق",
      checkInTime: "وقت الوصول",
      checkOutTime: "وقت المغادرة",
      cancellationPolicy: "سياسة الإلغاء",
      hoursBeforeCheckIn: "ساعة قبل الوصول",
      freeCancellation: "إلغاء مجاني",
      noReviews: "لا توجد تقييمات بعد",
      basedOnReviews: "مراجعة",
      perNight: "لليلة",
      perStay: "للإقامة",
      selectDates: "اختر التواريخ",
      proceedToBooking: "متابعة الحجز",
    },
    aboutUs: {
      title: "من نحن",
      story: "قصتنا",
      vision: "رؤيتنا",
      mission: "مهمتنا",
      values: "قيمنا",
      contactUs: "تواصل معنا",
      findUs: "تجدنا هنا",
      directions: "الاتجاهات",
    },
    guestAccount: {
      title: "حسابي",
      dashboard: "لوحة التحكم",
      overview: "نظرة عامة",
      profile: "الملف الشخصي",
      security: "الأمان",
      myBookings: "حجوزاتي",
      payments: "المدفوعات",
      favorites: "المفضلة",
      editProfile: "تعديل الملف",
      saveChanges: "حفظ التغييرات",
      noBookings: "لا توجد حجوزات",
      noFavorites: "لا توجد مفضلات",
      noPayments: "لا توجد مدفوعات بعد",
      noUpcoming: "لا توجد إقامات قادمة",
      saveFavorite: "حفظ",
      removeFavorite: "إزالة",
      bookingDetails: "تفاصيل الحجز",
      backToBookings: "العودة للحجوزات",
      viewAll: "عرض الكل",
      recentBookings: "الحجوزات الأخيرة",
      upcomingStays: "الإقامات القادمة",
      totalBookings: "إجمالي الحجوزات",
      totalSpent: "إجمالي الإنفاق",
      favoritesCount: "المفضلة",
      memberSince: "عضو منذ",
      accountInfo: "معلومات الحساب",
      accountEmail: "البريد الإلكتروني",
      accountPhone: "رقم الهاتف",
      accountRole: "نوع الحساب",
      changePassword: "تغيير كلمة المرور",
      currentPassword: "كلمة المرور الحالية",
      newPassword: "كلمة المرور الجديدة",
      confirmPassword: "تأكيد كلمة المرور",
      passwordTooShort: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
      passwordMismatch: "كلمتا المرور غير متطابقتين",
      passwordChanged: "تم تغيير كلمة المرور بنجاح",
      passwordIncorrect: "كلمة المرور الحالية غير صحيحة",
      sameAsOld: "كلمة المرور الجديدة يجب أن تختلف عن الحالية",
      paymentStatus: "حالة الدفع",
      amount: "المبلغ",
      paymentDate: "تاريخ الدفع",
      paid: "مدفوع",
      pendingPayment: "قيد الانتظار",
      refunded: "مُسترد",
      failed: "فاشل",
      lastPayment: "آخر دفعة",
    },
  },
  en: {
    dir: "ltr" as const,
    brand: { name: "Sewar AlAndalus", tagline: "Andalusian Elegance in Hospitality" },
    intro: {
      skip: "Skip Intro",
      progress: "Interactive Experience",
      scenes: [
        { title: "Sewar AlAndalus", subtitle: "Where the journey begins" },
        { title: "Approach the Hotel", subtitle: "Feel the welcome come alive around you" },
        { title: "The Lobby", subtitle: "A welcoming space with Andalusian grace" },
        { title: "Your Room Awaits", subtitle: "A luxurious stay inviting you to rest" },
      ],
      door: "Enter the Hotel",
      doorHint: "Click to begin your stay with Sewar AlAndalus",
    },
    nav: {
      links: [
        { id: "rooms", label: "Rooms & Suites" },
        { id: "featured", label: "Featured Hotels" },
        { id: "experiences", label: "Experiences" },
        { id: "why", label: "Why Us" },
        { id: "stories", label: "Guest Stories" },
        { id: "contact", label: "Contact" },
      ],
      cta: "Book Your Stay",
      allRooms: "All Rooms & Suites",
    },
    hero: {
      eyebrow: "Andalusian Elegance in Hospitality",
      title: "A Luxurious Stay, Told Like a Poem",
      subtitle:
        "Sewar AlAndalus — a refined hospitality destination gathering handpicked premium hotels, where Andalusian warmth meets the finest details of comfort.",
      ctaPrimary: "Find Your Room",
      ctaSecondary: "About Us",
      scroll: "Scroll Down",
    },
    about: {
      eyebrow: "Our Story",
      title: "A Legacy of Hospitality, Told Detail by Detail",
      lead: "Sewar AlAndalus was born from a passion to revive the spirit of Andalusian hospitality, where authentic craft meets the refinement of modern experience.",
      paragraphs: [
        "We believe a true stay begins in the very first moment. So we designed an integrated destination that gathers elite hotels under one roof, with expertise passed down through generations.",
        "Driven by our vision, we assembled the finest hotels and most skilled hospitality teams, making Sewar AlAndalus the leading destination for lovers of comfort and elegance.",
      ],
      signature: "Chairman of the Board",
      signatory: "Abu Mohammed Al-Andalusi",
    },
    vision: {
      eyebrow: "Vision & Mission",
      title: "Crafting the Region's Premier Hospitality Destination",
      body: "Our vision is to be the finest cluster of luxury hotels, leveraging our expertise and partnerships to offer an unforgettable stay emulated worldwide.",
      mission: {
        title: "Our Mission",
        body: "Our mission extends beyond providing rooms. We are committed to crafting an exceptional experience that supports tourism, revives the art of hospitality, and elevates the hotel sector in the Kingdom.",
      },
    },
    stats: {
      title: "Expertise That Bears Fruit",
      subtitle: "We turn vision into reality through hotels that raised hospitality standards.",
      items: [
        { value: 5, suffix: "", label: "Curated Hotels", prefix: "" },
        { value: 320, suffix: "+", label: "Rooms & Suites", prefix: "" },
        { value: 4.9, suffix: "", label: "Average Rating", prefix: "" },
        { value: 12, suffix: "", label: "Years of Hospitality", prefix: "" },
      ],
    },
    markets: {
      eyebrow: "Our Destinations",
      title: "Destinations That Capture Hearts",
      subtitle: "Discover our collection of hotels in the finest cities, where elegance meets comfort.",
      cta: "Discover Destination",
      items: [
        { name: "Sewar Riyadh", tag: "Riyadh", desc: "A luxury hotel in the heart of the capital with stunning city views." },
        { name: "Sewar Jeddah", tag: "Jeddah", desc: "A seafront stay touched by the breeze of the Red Sea." },
        { name: "Sewar Makkah", tag: "Makkah", desc: "Close to the Holy Mosque with hospitality worthy of the visitor." },
        { name: "Sewar Madinah", tag: "Madinah", desc: "Calm and serenity steps away from the Prophet's Mosque." },
        { name: "Sewar AlUla", tag: "AlUla", desc: "A desert retreat among mountains and historic ruins." },
        { name: "Sewar Red Sea", tag: "Red Sea", desc: "A coastal resort blending luxury with natural purity." },
      ],
    },
    experiences: {
      eyebrow: "Experiences",
      title: "Experiences Worth Living",
      subtitle: "Every detail in our hotels is designed to offer an unforgettable, complete journey.",
      items: [
        { title: "Wellness Spas", desc: "World-class spa and wellness facilities to restore balance and rest." },
        { title: "Fine Dining", desc: "Creative dishes from elite chefs in refined atmospheres." },
        { title: "Private Concierge", desc: "Royal concierge service around the clock for every detail of your stay." },
        { title: "Recreational Activities", desc: "Tours, events, and activities designed for every guest." },
      ],
    },
    values: {
      eyebrow: "Our Values",
      title: "Values That Inspire Every Stay",
      subtitle: "Five principles guiding our vision and shaping our identity.",
      items: [
        { title: "Hospitality", desc: "We welcome guests with the grace of authentic Andalusian tradition." },
        { title: "Mastery", desc: "In details that a discerning eye never misses." },
        { title: "Trust", desc: "Earning our guests' trust with full transparency." },
        { title: "Luxury", desc: "A refined experience from the first moment to the last." },
        { title: "Innovation", desc: "Blending hospitality's heritage with contemporary design." },
      ],
    },
    testimonials: {
      eyebrow: "Guest Stories",
      title: "Stories From Guests Who Lived the Experience",
      items: [
        { quote: "A wonderful stay by every measure, the service was exceptional!", name: "Ahmed Al-Otaibi", role: "Business Traveler" },
        { quote: "Luxury hotel in an excellent location with a professional team.", name: "Sara Al-Maliki", role: "Family Vacation" },
        { quote: "An unforgettable experience, we will definitely return.", name: "Khalid Al-Harbi", role: "Honeymoon" },
      ],
    },
    news: {
      eyebrow: "News",
      title: "Latest From Sewar AlAndalus",
      items: [
        { title: "Opening Sewar AlUla Among the Mountains", date: "November 2025", tag: "Opening" },
        { title: "Our Collection Expands to Six Cities", date: "October 2025", tag: "Business" },
        { title: "Partnership With Elite Global Chefs", date: "September 2025", tag: "Partnerships" },
      ],
    },
    contact: {
      eyebrow: "Contact Us",
      title: "Let's Craft Your Next Stay",
      subtitle: "For all booking and stay inquiries, we are here to serve you.",
      form: {
        subject: "Request Subject",
        subjectOptions: ["Booking Inquiry", "Hotel Inquiry", "General Inquiries", "Careers", "Customer Service"],
        name: "Full Name",
        email: "Email Address",
        phone: "Phone Number",
        message: "Your Message",
        consent: "I am committed to the Terms of Service and agree to the Privacy Policy",
        submit: "Send",
      },
      info: {
        email: "info@sewaralandalus.sa",
        phone: "+966 11 655 5555",
        address: "Riyadh, Kingdom of Saudi Arabia",
      },
    },
    footer: {
      about: "Sewar AlAndalus — a refined hospitality destination gathering handpicked hotels with the highest standards of elegance and comfort.",
      rights: "All Rights Reserved",
      newsletter: "Newsletter",
      newsletterCta: "Subscribe",
      quickLinks: "Quick Links",
    },
    auth: {
      loginTitle: "Log In",
      registerTitle: "Create Account",
      email: "Email Address",
      password: "Password",
      name: "Full Name",
      role: "Account Type",
      guest: "Guest",
      loginBtn: "Log In",
      registerBtn: "Register",
      noAccount: "Don't have an account?",
      haveAccount: "Already have an account?",
      registerLink: "Create one",
      loginLink: "Log in",
      adminLoginTitle: "Admin Portal Login",
      adminLoginSubtitle: "For platform staff only",
      adminPortalLink: "Admin login",
      wrongPortalAdmin: "This is an admin account. Please use the admin login page.",
      wrongPortalGuest: "This is a guest account. Please use the guest login page.",
    },
    search: {
      title: "Search Rooms",
      destination: "Destination",
      checkIn: "Check-in Date",
      checkOut: "Check-out Date",
      guests: "Number of Guests",
      searchBtn: "Search",
      noResults: "No rooms available for these dates",
      perNight: "per night",
      availableRooms: "rooms available",
      bookNow: "Book Now",
    },
    booking: {
      title: "Complete Booking",
      guestDetails: "Guest Details",
      fullName: "Full Name",
      email: "Email Address",
      phone: "Phone Number",
      payment: "Payment",
      orderSummary: "Order Summary",
      roomType: "Room Type",
      quantity: "Quantity",
      nights: "nights",
      total: "Total",
      confirmBooking: "Confirm Booking",
      confirmation: "Your booking has been confirmed",
      bookingId: "Booking ID",
      myBookings: "My Bookings",
      status: "Status",
      cancel: "Cancel",
      cancelConfirm: "Are you sure you want to cancel this booking?",
      cancelled: "Cancelled",
      refund: "Refund Amount",
    },
    dashboard: {
      title: "Management Dashboard",
      overview: "Overview",
      rooms: "Rooms",
      calendar: "Calendar",
      bookings: "Bookings",
      roomTypes: "Room Types",
      rates: "Rates",
      addRoomType: "Add Room Type",
      addRoom: "Add Room",
      roomNumber: "Room Number",
      floor: "Floor",
      capacity: "Capacity",
      basePrice: "Base Price",
      bedType: "Bed Type",
      checkIn: "Check-in",
      checkOut: "Check-out",
      payouts: "Payouts",
      occupancyRate: "Occupancy Rate",
      adr: "ADR (Avg Daily Rate)",
      revpar: "RevPAR",
      revenue: "Revenue",
      cancellations: "Cancellations",
      recentBookings: "Recent Bookings",
      upcomingArrivals: "Upcoming Arrivals",
      upcomingDepartures: "Upcoming Departures",
      selectPeriod: "Select Period",
      selectProperty: "Select Property",
      noRooms: "No rooms yet",
      noBookings: "No bookings yet",
      noRates: "No rates yet",
      mediaManager: "Media Manager",
      uploadImage: "Upload Image",
      captionAr: "Arabic Caption",
      captionEn: "English Caption",
      reorder: "Reorder",
      deleteImage: "Delete",
      galleryTitle: "Gallery",
    },
    admin: {
      title: "Admin Console",
      hotels: "Hotels",
      users: "Users",
      reports: "Reports",
      approve: "Approve",
      suspend: "Suspend",
      reinstate: "Reinstate",
      pending: "Pending",
      active: "Active",
      suspended: "Suspended",
      totalBookings: "Total Bookings",
      totalRevenue: "Total Revenue",
      cancellationRate: "Cancellation Rate",
      featured: "Featured",
      curateFeatured: "Manage Featured Hotels",
      addFeatured: "Add to Featured",
      removeFeatured: "Remove from Featured",
      reorderFeatured: "Reorder Featured",
      disputeCount: "Dispute Count",
      platformReports: "Platform Reports",
      perHotel: "Per Hotel",
      roomsManagement: "Rooms & Suites Management",
      addUser: "Add User",
      userDetails: "User Details",
      searchUsers: "Search users...",
      email: "Email",
      phone: "Phone",
      role: "Role",
      status: "Status",
      joined: "Joined",
      guest: "Guest",
      adminRole: "Admin",
      bookings: "Bookings",
      favorites: "Favorites",
      totalSpent: "Total Spent",
      noResults: "No results",
      addRoomType: "Add Room Type",
      roomNameAr: "Name (Arabic)",
      roomNameEn: "Name (English)",
      roomDescAr: "Description (Arabic)",
      roomDescEn: "Description (English)",
      capacity: "Capacity",
      bedType: "Bed Type",
      pricePerNight: "Price per night",
      amenities: "Amenities",
      photos: "Photos (comma-separated URLs)",
      photosHint: "Paste image URLs separated by comma",
      photoUrl: "Photo URL",
      addPhoto: "Add photo",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      deleting: "Deleting...",
      confirmDeleteRoom: "Delete this room type? This action cannot be undone.",
      cannotDeleteBooked: "This room type has bookings and cannot be deleted.",
      roomAdded: "Room type added successfully",
      existingRooms: "Existing Room Types",
      selectHotel: "Select Hotel",
      noHotels: "No hotels",
      confirmSuspend: "Suspend this account?",
      confirmReinstate: "Reinstate this account?",
    },
    hotelHome: {
      featuredTitle: "Featured Hotels",
      featuredSubtitle: "Discover our handpicked selection of premium hotels",
      viewDetails: "View Details",
      startingFrom: "Starting from",
      perNight: "per night",
      rating: "Rating",
      reviewsCount: "reviews",
      searchPlaceholder: "Search for a hotel...",
      exploreMore: "Explore More",
      noFeatured: "No featured hotels available",
      collections: "Collections",
      experiences: "Experiences",
      trustSignals: "Why Choose Us",
    },
    propertyDetail: {
      gallery: "Photo Gallery",
      amenities: "Amenities",
      availableRooms: "Available Rooms",
      reviews: "Reviews",
      location: "Location",
      getDirections: "Get Directions",
      nearbyLandmarks: "Nearby Landmarks",
      hostInfo: "Host Information",
      policies: "Hotel Policies",
      checkInTime: "Check-in Time",
      checkOutTime: "Check-out Time",
      cancellationPolicy: "Cancellation Policy",
      hoursBeforeCheckIn: "hours before check-in",
      freeCancellation: "Free cancellation",
      noReviews: "No reviews yet",
      basedOnReviews: "reviews",
      perNight: "per night",
      perStay: "per stay",
      selectDates: "Select Dates",
      proceedToBooking: "Proceed to Booking",
    },
    aboutUs: {
      title: "About Us",
      story: "Our Story",
      vision: "Our Vision",
      mission: "Our Mission",
      values: "Our Values",
      contactUs: "Contact Us",
      findUs: "Find Us Here",
      directions: "Directions",
    },
    guestAccount: {
      title: "My Account",
      dashboard: "Dashboard",
      overview: "Overview",
      profile: "Profile",
      security: "Security",
      myBookings: "My Bookings",
      payments: "Payments",
      favorites: "Favorites",
      editProfile: "Edit Profile",
      saveChanges: "Save Changes",
      noBookings: "No bookings yet",
      noFavorites: "No favorites yet",
      noPayments: "No payments yet",
      noUpcoming: "No upcoming stays",
      saveFavorite: "Save",
      removeFavorite: "Remove",
      bookingDetails: "Booking Details",
      backToBookings: "Back to Bookings",
      viewAll: "View all",
      recentBookings: "Recent Bookings",
      upcomingStays: "Upcoming Stays",
      totalBookings: "Total Bookings",
      totalSpent: "Total Spent",
      favoritesCount: "Favorites",
      memberSince: "Member since",
      accountInfo: "Account Info",
      accountEmail: "Email",
      accountPhone: "Phone",
      accountRole: "Account Type",
      changePassword: "Change Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmPassword: "Confirm Password",
      passwordTooShort: "Password must be at least 8 characters",
      passwordMismatch: "Passwords do not match",
      passwordChanged: "Password changed successfully",
      passwordIncorrect: "Current password is incorrect",
      sameAsOld: "New password must differ from the current one",
      paymentStatus: "Payment Status",
      amount: "Amount",
      paymentDate: "Payment Date",
      paid: "Paid",
      pendingPayment: "Pending",
      refunded: "Refunded",
      failed: "Failed",
      lastPayment: "Last payment",
    },
  },
} as const;

export type Content = (typeof content)["ar"];
